<a href="https://colab.research.google.com/github/Deepak-Acharya/Machine-leaning-Basic-/blob/Learning-the-basics/Matrix_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Matrix using numpy

In [ ]:
matrix_1 = np.array([[2,3],[4,6]])
print(matrix_1)

[[2 3]
 [4 6]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[2,5,8],[22,33,11],[20,15,90]])
print(matrix_2)

[[ 2  5  8]
 [22 33 11]
 [20 15 90]]


Creating matrix with random value

In [ ]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.65692782 0.19932126 0.38784653]
 [0.2908991  0.02235506 0.60775126]
 [0.17483848 0.94538679 0.52371277]]


In [ ]:
random_matrix_int = np.random.randint(100,size =(4,5))
print(random_matrix_int)

[[23 39 20 56 51]
 [92  8 78 19 57]
 [77 86 40 49 45]
 [82 11 43 35 75]]


Matrix with all the ones

In [ ]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


Null Matrix

In [ ]:
matrix_4 = np.zeros((4,4),dtype =int)
print(matrix_4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity Matrix

In [ ]:
imatrix = np.eye(3,3)
print(imatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of matrix

In [ ]:
a = np.random.randint(100 , size = (4,5))
print(a)

[[48 61 92 18  4]
 [91 95 44 33 91]
 [82  1 56 73 19]
 [60 43 67 48 98]]


In [ ]:
transpose = np.transpose(a)
print(transpose)

[[48 91 82 60]
 [61 95  1 43]
 [92 44 56 67]
 [18 33 73 48]
 [ 4 91 19 98]]


Matrix Addition

In [ ]:
a = np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

sum = a+b
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
A = np.random.randint(100 ,size= (4,3))
B  = np.random.randint(200, size = (4,3))

sum = A+B
print(sum)

[[ 82  99  86]
 [112 111 182]
 [101 201  74]
 [200 225 163]]


Matrix Subtraction

In [ ]:
difference = A-B
print(difference)

[[ -50  -21  -42]
 [  54   65  -48]
 [  63  -23   32]
 [-168 -105 -121]]


Multiplying a Matrix with scalar


In [ ]:
x = 6
y  = np.random.randint(20 , size =(4,4))

z = np.multiply(x,y)
print(z)

[[ 90  36 102 108]
 [ 54  60  84   0]
 [  0 108  12   0]
 [ 30  12  36  90]]


Multiplying two matrix

In [ ]:
A = np.random.randint(100 ,size= (4,3))
B  = np.random.randint(200, size = (3,3))

mutiply = np.dot(A,B)
print(mutiply)

[[34438 27238  9720]
 [21581 18461  3832]
 [22618 24898  6400]
 [22612 23830  9674]]
